# SPDX-FileCopyrightText: 2025 Knitli Inc.
# SPDX-FileCopyrightText: 2025 Knitli Inc. <knitli@knit.li>
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

line_ending: lf
gitignore_excludes: true
format:
  trim_trailing_whitespace: true
