# SPDX-FileCopyrightText: 2025 Knitli Inc. <knitli@knit.li>
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[default]
locale = "en-us"
check-file = true
check-filename = true
extend-ignore-re = [
  "(?s)(#|//)\\s*spellchecker:off.*?\\n\\s*(#|//)\\s*spellchecker:on",
]
[default.extend-words]
edn = "edn"
i18n = "i18n"
i18n-t = "i18n-t"
i18n-tc = "i18n-tc"
i18next = "i18next"
iif = "iif"
iife = "iife"
mak = "mak"
strat = "strat"
typ = "typ"

[files]
ignore-hidden = false
ignore-files = true
extend-exclude = [
  ".git",
  ".venv/**/*",
  "/**/node_modules/**",
  "/tmp/**/*",
  "/usr/**/*",
  "/usr/share/code/**/*",
  "context/apis/complete_docs/**/*",
  "docs/manifest.json",
  "eslint.config.mjs",
  "external",
  "license-list-data",
  "mkdocs-material",
  "node_modules",
  "src/assets/fonts/**/*",
  "src/assets/images/**/*",
  "src/assets/videos/**/*",
  "vendor",
]
