# SPDX-FileCopyrightText: 2025 Knitli Inc.
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[tools]
ast-grep = "latest"
gh = "latest"
gitsign = "latest"
hk = "latest"
node = "latest"
"pipx:reuse" = "latest"
pkl = "latest"
ripgrep = "latest"
ruff = "latest"
taplo = "latest"
typos = "latest"
uv = "latest"

[env]
GH_REPO="knitli/code-weaver-mcp"
