# SPDX-FileCopyrightText: 2025 Knitli Inc.
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: MIT OR Apache-2.0
# CodeWeaver Documentation Configuration
# World-class documentation for an extensible MCP server
site_name: CodeWeaver
site_description: Codeweaver -- The MCP Context Platform -- Official Documentation
site_author: Knitli Inc.
site_url: https://docs.codeweaver.dev
repo_url: https://github.com/knitli/codeweaver-mcp
repo_name: knitli/codeweaver-mcp
edit_uri: edit/main/docs/
# Copyright and Legal
copyright: |
  Copyright &copy; 2025 Knitli Inc. License: MIT <strong>or</strong> Apache-2.0.
# Theme Configuration - Material Design
theme:
  name: material
  # Logo and Branding
  logo: assets/knitli_symbol_off-white_RGB.svg
  favicon: assets/favicon-32x32.png
  custom_dir: overrides

  # Language and Internationalization
  language: en
  # Material Theme Features
  features:
    # Navigation Features
    - navigation.instant # Instant loading
    - navigation.instant.prefetch # Prefetch on hover
    - navigation.instant.progress # Instant loading progress
    - navigation.tracking # Track URL fragments
    - navigation.tabs # Top-level navigation tabs
    - navigation.tabs.sticky # Sticky navigation tabs
    - navigation.sections # Section navigation
    - navigation.expand # Auto-expand navigation
    - navigation.path # Navigation breadcrumbs
    - navigation.prune # Prune navigation for performance
    - navigation.indexes # Section index pages
    - navigation.top # Back to top button
    # Search Features
    - search.highlight # Highlight search terms
    - search.share # Share search results
    - search.suggest # Search suggestions
    # Header Features
    - header.autohide # Auto-hide header on scroll
    # Content Features
    - content.code.copy # Copy code button
    - content.code.select # Select code button
    - content.code.annotate # Code annotations
    - content.tabs.link # Link content tabs
    - content.tooltips # Content tooltips
    - content.footnote.tooltips # Footnote tooltips
    # Table of Contents
    - toc.follow # Follow table of contents
    - toc.integrate # Integrate TOC with navigation
  # Color Palette - Knitli Brand Colors
  palette:
    # Light mode - warm and human-centered
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode - sophisticated aubergine theme
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  # Fonts - Human-centered and accessible
  font:
    text: Inter  # Excellent readability and accessibility
    code: SF Mono  # Clean, readable monospace
  # Custom CSS and JavaScript
  custom_css: assets/extra.css
# Navigation Structure - Developer-First Architecture
# NOTE: For nav see docs/.nav.yml
# Plugins Configuration
plugins:
  # Generate API documentation (gen-files creates virtual API pages for mkdocstrings)
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  # Search
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

  # Automatic API documentation generation
  - mkdocstrings:
      handlers:
        python:
          options:
            # Source code settings
            show_source: true
            show_root_heading: true
            show_root_toc_entry: true
            show_root_full_path: false
            show_object_full_path: false
            # Member settings
            show_bases: true
            show_inheritance_diagram: true
            show_if_no_docstring: true
            # Docstring settings
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
              trim_doctest_flags: true
            # Type annotation settings
            show_signature_annotations: true
            separate_signature: true
            # Filter settings
            filters:
              - "!^_[^_]" # Hide private members except __special__
            # Rendering settings
            group_by_category: true
            heading_level: 4
  # Git integration for last updated dates
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      type: timeago
      custom_format: "%d. %B %Y"
      timezone: UTC
      locale: en
      strict: false
  # Auto-generated navigation
  - awesome-nav
  - meta:
      enabled: true
  # Minification for performance
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
      js_files:
        - assets/format_blocks.js
        - assets/sort_tables.js
      css_files:
        - assets/extra.css
  # Social cards generation - Knitli branded
  - social:
      enabled: !ENV [CI, false]
      cards_layout_options:
        background_color: "#ea5932"  # Knitli rust-orange
        color: "#f2ece7"  # Knitli off-white
        font_family: Inter
  # Tags for content organization
  - tags:
      enabled: true
      tags_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  # RSS feed generation
  - rss:
      enabled: !ENV [CI, false]
      match_path: "reference/changelog.*"
      date_from_meta:
        as_creation: date
      categories:
        - tags
        - categories
# Markdown Extensions
markdown_extensions:
  # Python Markdown Extensions
  - abbr # Abbreviations
  - admonition # Admonitions (notes, warnings, etc.)
  - attr_list # Attribute lists
  - def_list # Definition lists
  - footnotes # Footnotes
  - md_in_html # Markdown in HTML
  - toc: # Table of contents
      permalink: true
      permalink_title: "Anchor link to this section"
      title: "On this page"
      toc_depth: 3
  - tables # Tables
  # PyMdown Extensions
  - pymdownx.betterem: # Better emphasis
      smart_enable: all
  - pymdownx.caret # Insertions and superscript
  - pymdownx.details # Collapsible details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight: # Syntax highlighting
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
      auto_title: true
      linenums: true
  - pymdownx.inlinehilite # Inline syntax highlighting
  - pymdownx.keys # Keyboard keys
  - pymdownx.mark # Highlighting text
  - pymdownx.smartsymbols # Smart symbols
  - pymdownx.snippets # Include snippets
    # auto_append:
    #- includes/abbreviations.md
    # check_paths: true
  - pymdownx.superfences: # Nested code blocks
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed: # Content tabs
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist: # Task lists
      custom_checkbox: true
  - pymdownx.tilde # Deletions and subscript
# Validation and Quality Assurance
validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: info
  links:
    not_found: warn
    absolute_links: info
    unrecognized_links: info
# Watch settings for development
watch:
  - docs
  - mkdocs.yml
# Extra configuration
extra:
  # Analytics
  analytics:
    provider: google
    property: !ENV [GOOGLE_ANALYTICS_KEY, ""]
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback! Help us improve by <a href="https://github.com/knitli/codeweaver-mcp/issues/new/?title=[Docs]+{title}+-+{url}" target="_blank" rel="noopener">


              telling us what you found helpful
            </a>.
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve by <a href="https://github.com/knitli/codeweaver-mcp/issues/new/?title=[Docs]+{title}+-+{url}" target="_blank" rel="noopener">


              telling us what we can do better
            </a>.
  # Social links
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/knitli/codeweaver-mcp
      name: GitHub Repository
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/codeweaver/
      name: PyPI Package
    - icon: fontawesome/solid/paper-plane
      link: mailto:support@knit.li
      name: Email Support
  # Version management
  version:
    provider: mike
    default: latest
  # Consent for cookies/analytics
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well as to measure the effectiveness of our documentation and whether users find what they're searching for. With your consent, you're helping us to make our documentation better.
# Extra CSS and JavaScript
extra_css:
  - assets/extra.css
extra_javascript:
  - assets/format_blocks.js
  - assets/sort_tables.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
# Development server configuration
dev_addr: '127.0.0.1:8000'
use_directory_urls: true
strict: false
