# SPDX-FileCopyrightText: 2025 Knitli Inc.
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

# CodeWeaver Documentation Configuration
# World-class documentation for an extensible MCP server

site_name: CodeWeaver Documentation
site_description: Extensible semantic code search with plugin architecture - Official Documentation
site_author: Knitli Inc.
site_url: https://docs.codeweaver.dev
repo_url: https://github.com/knitli/code-weaver-mcp
repo_name: knitli/code-weaver-mcp
edit_uri: edit/main/docs/

# Copyright and Legal
copyright: |
  Copyright &copy; 2025 Knitli Inc. Licensed under MIT OR Apache-2.0.
  
# Theme Configuration - Material Design
theme:
  name: material
  
  # Logo and Branding
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  
  # Language and Internationalization
  language: en
  
  # Material Theme Features
  features:
    # Navigation Features
    - navigation.instant      # Instant loading
    - navigation.instant.prefetch  # Prefetch on hover
    - navigation.tracking     # Track URL fragments
    - navigation.tabs         # Top-level navigation tabs
    - navigation.tabs.sticky  # Sticky navigation tabs
    - navigation.sections     # Section navigation
    - navigation.expand       # Auto-expand navigation
    - navigation.path         # Navigation breadcrumbs
    - navigation.prune        # Prune navigation for performance
    - navigation.indexes      # Section index pages
    - navigation.top          # Back to top button
    
    # Search Features
    - search.highlight        # Highlight search terms
    - search.share           # Share search results
    - search.suggest         # Search suggestions
    
    # Header Features
    - header.autohide        # Auto-hide header on scroll
    
    # Content Features
    - content.code.copy      # Copy code button
    - content.code.select    # Select code button
    - content.code.annotate  # Code annotations
    - content.tabs.link      # Link content tabs
    - content.tooltips       # Content tooltips
    - content.footnote.tooltips  # Footnote tooltips
    
    # Table of Contents
    - toc.follow            # Follow table of contents
    - toc.integrate         # Integrate TOC with navigation
    
  # Color Palette
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  # Fonts
  font:
    text: Inter
    code: JetBrains Mono
  
  # Custom CSS and JavaScript
  custom_dir: docs/overrides

# Navigation Structure - Progressive Disclosure & Task-Oriented
nav:
  # LEVEL 1: Getting Started (High-Level Overview)
  - Home: index.md
  - Why CodeWeaver?: why-codeweaver.md
  - Getting Started:
    - Quick Start: getting-started/quick-start.md
    - Installation: getting-started/installation.md
    - Your First Search: getting-started/first-search.md
    - Configuration Basics: getting-started/configuration.md
  
  # LEVEL 2: User Guides (Task-Oriented)
  - User Guide:
    - Overview: user-guide/index.md
    - Indexing Your Codebase: user-guide/indexing.md
    - Search Strategies: user-guide/search-strategies.md
    - Advanced Filtering: user-guide/filtering.md
    - MCP Integration: user-guide/mcp-integration.md
    - Performance Optimization: user-guide/performance.md
    - Troubleshooting: user-guide/troubleshooting.md
  
  # LEVEL 3: Configuration (Deep Configuration)
  - Configuration:
    - Overview: configuration/index.md
    - Configuration File: configuration/config-file.md
    - Environment Variables: configuration/environment.md
    - Provider Configuration: configuration/providers.md
    - Backend Configuration: configuration/backends.md
    - Service Configuration: configuration/services.md
    - Advanced Settings: configuration/advanced.md
    - Migration Guide: configuration/migration.md
  
  # LEVEL 4: Architecture (System Understanding)
  - Architecture:
    - Overview: architecture/index.md
    - Core Concepts: architecture/concepts.md
    - Plugin System: architecture/plugins.md
    - Factory Pattern: architecture/factory-system.md
    - Service Layer: architecture/services.md
    - Protocol Interfaces: architecture/protocols.md
    - Middleware: architecture/middleware.md
    - Type System: architecture/types.md
    - Design Decisions: architecture/decisions.md
  
  # LEVEL 5: Plugin Development (Advanced Users)
  - Plugin Development:
    - Overview: plugins/index.md
    - Getting Started: plugins/getting-started.md
    - Plugin Types:
      - Embedding Providers: plugins/embedding-providers.md
      - Vector Backends: plugins/vector-backends.md
      - Data Sources: plugins/data-sources.md
      - Services: plugins/services.md
    - Advanced Topics:
      - Plugin Protocols: plugins/protocols.md
      - Registration System: plugins/registration.md
      - Testing Plugins: plugins/testing.md
      - Performance Guidelines: plugins/performance.md
    - Examples:
      - Custom Provider: plugins/examples/custom-provider.md
      - Custom Backend: plugins/examples/custom-backend.md
      - Custom Service: plugins/examples/custom-service.md
  
  # LEVEL 6: API Reference (Detailed Reference)
  - API Reference:
    - Overview: api/index.md
    - MCP Tools:
      - index_codebase: api/tools/index-codebase.md
      - search_code: api/tools/search-code.md
      - ast_grep_search: api/tools/ast-grep-search.md
      - get_supported_languages: api/tools/supported-languages.md
    - Core APIs:
      - CodeWeaverFactory: api/core/factory.md
      - ConfigManager: api/core/config.md
      - ServicesManager: api/core/services.md
    - Protocols:
      - VectorBackend: api/protocols/vector-backend.md
      - EmbeddingProvider: api/protocols/embedding-provider.md
      - DataSource: api/protocols/data-source.md
      - ServiceProvider: api/protocols/service-provider.md
    - Types:
      - Data Structures: api/types/data-structures.md
      - Enums: api/types/enums.md
      - Exceptions: api/types/exceptions.md
      - Configuration: api/types/configuration.md
  
  # LEVEL 7: Tutorials & Examples (Learning by Doing)
  - Tutorials:
    - Overview: tutorials/index.md
    - Basic Tutorials:
      - Setting Up Claude Desktop: tutorials/claude-desktop-setup.md
      - Indexing a React Project: tutorials/react-project.md
      - Multi-Language Codebase: tutorials/multi-language.md
      - Performance Tuning: tutorials/performance-tuning.md
    - Advanced Tutorials:
      - Custom Embedding Provider: tutorials/custom-embedding.md
      - Multi-Source Integration: tutorials/multi-source.md
      - Enterprise Deployment: tutorials/enterprise-setup.md
      - CI/CD Integration: tutorials/cicd-integration.md
    - Use Cases:
      - AI Assistant Integration: tutorials/use-cases/ai-assistant.md
      - Code Review Assistant: tutorials/use-cases/code-review.md
      - Documentation Generator: tutorials/use-cases/doc-generator.md
      - Legacy Code Analysis: tutorials/use-cases/legacy-analysis.md
  
  # LEVEL 8: Reference Materials (Quick Lookups)
  - Reference:
    - Language Support: reference/language-support.md
    - Provider Comparison: reference/provider-comparison.md
    - Backend Comparison: reference/backend-comparison.md
    - Configuration Schema: reference/config-schema.md
    - Environment Variables: reference/environment-vars.md
    - Error Codes: reference/error-codes.md
    - Performance Benchmarks: reference/benchmarks.md
    - Changelog: reference/changelog.md
  
  # LEVEL 9: Community & Support (Ecosystem)
  - Community:
    - Contributing: community/contributing.md
    - Code of Conduct: community/code-of-conduct.md
    - Support: community/support.md
    - Roadmap: community/roadmap.md
    - Security: community/security.md
    - License: community/license.md

# Plugins Configuration
plugins:
  # Search
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      
  # Automatic API documentation generation
  - mkdocstrings:
      handlers:
        python:
          options:
            # Source code settings
            show_source: true
            show_root_heading: true
            show_root_toc_entry: true
            show_root_full_path: false
            show_object_full_path: false
            
            # Member settings
            show_bases: true
            show_inheritance_diagram: true
            show_if_no_docstring: true
            
            # Docstring settings
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
              trim_doctest_flags: true
              
            # Type annotation settings
            show_signature_annotations: true
            separate_signature: true
            
            # Filter settings
            filters:
              - "!^_[^_]"  # Hide private members except __special__
              
            # Rendering settings
            group_by_category: true
            heading_level: 2
  
  # Git integration for last updated dates
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      type: timeago
      custom_format: "%d. %B %Y"
      timezone: UTC
      locale: en
      strict: false
  
  # Auto-generated navigation
  - awesome-pages:
      filename: .pages
      collapse_single_pages: true
      strict: false
  
  # Minification for performance
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
  
  # Social cards generation
  - social:
      enabled: !ENV [CI, false]
      cards_layout_options:
        background_color: "#1976d2"
        font_family: Inter
  
  # Tags for content organization
  - tags:
      tags_file: reference/tags.md
  
  # RSS feed generation
  - rss:
      enabled: !ENV [CI, false]
      match_path: "reference/changelog.*"
      date_from_meta:
        as_creation: date
      categories:
        - tags
        - categories

# Markdown Extensions
markdown_extensions:
  # Python Markdown Extensions
  - abbr                    # Abbreviations
  - admonition             # Admonitions (notes, warnings, etc.)
  - attr_list              # Attribute lists
  - def_list               # Definition lists
  - footnotes              # Footnotes
  - md_in_html             # Markdown in HTML
  - toc:                   # Table of contents
      permalink: true
      permalink_title: "Anchor link to this section"
      title: "On this page"
      toc_depth: 3
  - tables                 # Tables
  
  # PyMdown Extensions
  - pymdownx.arithmatex:   # Math notation
      generic: true
  - pymdownx.betterem:     # Better emphasis
      smart_enable: all
  - pymdownx.caret         # Insertions and superscript
  - pymdownx.details       # Collapsible details
  - pymdownx.emoji:        # Emoji support
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:    # Syntax highlighting
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
      auto_title: true
      linenums: true
  - pymdownx.inlinehilite  # Inline syntax highlighting
  - pymdownx.keys          # Keyboard keys
  - pymdownx.mark          # Highlighting text
  - pymdownx.smartsymbols  # Smart symbols
  - pymdownx.snippets:     # Include snippets
      auto_append:
        - includes/abbreviations.md
      check_paths: true
  - pymdownx.superfences:  # Nested code blocks
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:       # Content tabs
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:     # Task lists
      custom_checkbox: true
  - pymdownx.tilde         # Deletions and subscript

# Validation and Quality Assurance
validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: info
  links:
    not_found: warn
    absolute_links: info
    unrecognized_links: info

# Watch settings for development
watch:
  - src/codeweaver
  - docs/overrides
  - mkdocs.yml

# Extra configuration
extra:
  # Analytics
  analytics:
    provider: google
    property: !ENV [GOOGLE_ANALYTICS_KEY, ""]
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback! Help us improve by 
            <a href="https://github.com/knitli/code-weaver-mcp/issues/new/?title=[Docs]+{title}+-+{url}" target="_blank" rel="noopener">
              telling us what you found helpful
            </a>.
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve by 
            <a href="https://github.com/knitli/code-weaver-mcp/issues/new/?title=[Docs]+{title}+-+{url}" target="_blank" rel="noopener">
              telling us what we can do better
            </a>.
  
  # Social links
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/knitli/code-weaver-mcp
      name: GitHub Repository
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/codeweaver/
      name: PyPI Package
    - icon: fontawesome/brands/discord
      link: https://discord.gg/codeweaver
      name: Discord Community
    - icon: fontawesome/solid/paper-plane
      link: mailto:support@codeweaver.dev
      name: Email Support
  
  # Version management
  version:
    provider: mike
    default: latest
  
  # Consent for cookies/analytics
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

# Extra CSS and JavaScript
extra_css:
  - assets/extra.css
  - assets/api-docs.css

extra_javascript:
  - assets/extra.js
  - assets/mermaid.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Development server configuration
dev_addr: '127.0.0.1:8000'
use_directory_urls: true
strict: false