# SPDX-FileCopyrightText: 2025 Knitli Inc.
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[project]
authors = [
    { name = "Knitli Inc.", email = "knitli@knit.li" },
    { name = "Adam Poulemanos", email = "adam@knit.li" },
]
name = "codeweaver"
license = { text = "MIT OR Apache-2.0" }
keywords = [
    "code-indexing",
    "code-search",
    "ast-grep",
    "qdrant",
    "mcp",
    "plugin",
    "middleware",
    "voyageai",
    "code-embeddings",
    "semantic-search",
    "tree-sitter",
]

version = "0.1.0"
description = "Extensible MCP server for semantic code search with plugin architecture supporting multiple embedding providers, vector databases, and data sources."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ast-grep-py>=0.39.1",
    "fastmcp>=2.10.6",
    "qdrant-client>=1.15.0",
    "rignore>=0.6.4",
    "watchdog>=6.0.0",
    "voyageai>=0.3.4",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.1",
    "rich>=14.0.0",
]


[project.scripts]
code-weaver = "code_weaver:main"

[build-system]
requires = ["uv_build>=0.8.2,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
test = [
    "docarray>=0.40.1",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.1.0",
    "pytest-cov>=6.2.1",
    "pytest-mock>=3.14.1",
    "httpx>=0.28.1",
    "pytest-env>=1.1.5",
    "pytest-flakefinder>=1.1.0",
    "pytest-httpx>=0.35.0",
    "pytest-report>=0.2.1",
    "pytest-timeout>=2.4.0",
]
docs = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.15",
    "mkdocs-redirects>=1.0.0",
    "mkdocs-minify-plugin>=0.8.0",
    "mkdocs-awesome-pages-plugin>=2.10.0",
    "mkdocs-material-extensions>=1.2.0",
    "pymdown-extensions>=10.1",
]
dev = [
    "ruff>=0.12.4",
    "superclaude>=3.0.0.2",
    "uv_build>=0.8.2,<0.9.0",
    "uv>=0.8.2,<0.9.0",
    "ipython>=9.4.0",
]
typing = ["pylance>=0.32.0"]
