# SPDX-FileCopyrightText: 2025 Knitli Inc.
# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>

version = 1

# This file tracks the licenses for the grammars used in Codeweaver.

# If you're wondering why some paths are seemingly redundant, it's because REUSE disagrees...

[[annotations]]
path = ["parsers/bash/**"]
SPDX-FileCopyrightText = "Copyright (c) 2017 Max Brunsfeld"
SPDX-License-Identifier = "MIT"
file = "parsers/bash/LICENSE"

[[annotations]]
path = ["parsers/c/**"]
SPDX-FileCopyrightText = "Copyright (c) 2014 Max Brunsfeld"
SPDX-License-Identifier = "MIT"
file = "parsers/c/LICENSE"

[[annotations]]
path = ["parsers/cpp/**"]
SPDX-FileCopyrightText = "Copyright (c) 2014 Max Brunsfeld"
SPDX-License-Identifier = "MIT"
file = "parsers/cpp/LICENSE"

[[annotations]]
path = ["parsers/csharp/**"]
SPDX-FileCopyrightText = "Copyright (c) 2014-2023 Max Brunsfeld, Damien Guard, Amaan Qureshi, and contributors"
SPDX-License-Identifier = "MIT"
file = "parsers/csharp/LICENSE"

[[annotations]]
path = ["parsers/css/**"]
SPDX-FileCopyrightText = "Copyright (c) 2018 Max Brunsfeld"
SPDX-License-Identifier = "MIT"
file = "parsers/css/LICENSE"

[[annotations]]
path = [
    "parsers/elixir/scanner.c",
    "parsers/elixir/grammar.json",
    "parsers/elixir/parser.c",
    "parsers/elixir/NOTICE",
]
SPDX-FileCopyrightText = "Copyright 2021 The Elixir Team"
SPDX-License-Identifier = "Apache-2.0"
file = "parsers/elixir/LICENSE"

[[annotations]]
path = ["parsers/elixir/node-types.json", "parsers/elixir/tree_sitter/*"]
SPDX-FileCopyrightText = "Copyright (c) 2018-2021 Max Brunsfeld"
SPDX-License-Identifier = "MIT"
file = "parsers/elixir/NOTICE"

[[annotations]]
path = ["parsers/go/**"]
SPDX-FileCopyrightText = "Copyright (c) 2014 Max Brunsfeld"
SPDX-License-Identifier = "MIT"
file = "parsers/go/LICENSE"

[[annotations]]
path = ["parsers/haskell/**", "parsers/haskell/grammar.json", "parsers/haskell/node-types.json"]
SPDX-FileCopyrightText = "Copyright (c) 2014 Max Brunsfeld"
SPDX-License-Identifier = "MIT"
file = "parsers/haskell/LICENSE"

[[annotations]]
path = ["parsers/html/**"]
SPDX-FileCopyrightText = "Copyright (c) 2014 Max Brunsfeld"
SPDX-License-Identifier = "MIT"
file = "parsers/html/LICENSE"

[[annotations]]
path = ["parsers/java/**"]
SPDX-FileCopyrightText = "Copyright (c) 2017 Ayman Nadeem"
SPDX-License-Identifier = "MIT"
file = "parsers/java/LICENSE"

[[annotations]]
path = ["parsers/javascript/**"]
SPDX-FileCopyrightText = "Copyright (c) 2014 Max Brunsfeld"
SPDX-License-Identifier = "MIT"
file = "parsers/javascript/LICENSE"

[[annotations]]
path = ["parsers/json/**"]
SPDX-FileCopyrightText = "Copyright (c) 2014 Max Brunsfeld"
SPDX-License-Identifier = "MIT"
file = "parsers/json/LICENSE"

[[annotations]]
path = ["parsers/kotlin/**"]
SPDX-FileCopyrightText = "Copyright (c) 2024 Amaan Qureshi <amaanq12@gmail.com>"
SPDX-License-Identifier = "MIT"
file = "parsers/kotlin/LICENSE"

[[annotations]]
path = ["parsers/lua/**"]
SPDX-FileCopyrightText = "Copyright (c) 2021 Munif Tanjim"
SPDX-License-Identifier = "MIT"
file = "parsers/lua/LICENSE.md"

[[annotations]]
path = ["parsers/nix/**", "parsers/nix/grammar.json", "parsers/nix/node-types.json"]
SPDX-FileCopyrightText = "Copyright (c) 2019 Charles Strahan"
SPDX-License-Identifier = "MIT"
file = "parsers/nix/LICENSE"

[[annotations]]
path = ["parsers/php/**", "parsers/php_strict/**"]
SPDX-FileCopyrightText = "Copyright (c) 2017 Josh Vera, Github; Copyright (c) 2019 Max Brunsfeld, Amaan Qureshi, Christian Frøystad, Caleb White"
SPDX-License-Identifier = "MIT"
file = "parsers/php/LICENSE"

[[annotations]]
path = ["parsers/python/**"]
SPDX-FileCopyrightText = "Copyright (c) 2016 Max Brunsfeld"
SPDX-License-Identifier = "MIT"
file = "parsers/python/LICENSE"

[[annotations]]
path = ["parsers/ruby/**"]
SPDX-FileCopyrightText = "Copyright (c) 2016 Rob Rix"
SPDX-License-Identifier = "MIT"
file = "parsers/ruby/LICENSE"

[[annotations]]
path = ["parsers/rust/**"]
SPDX-FileCopyrightText = "Copyright (c) 2017 Maxim Sokolov"
SPDX-License-Identifier = "MIT"
file = "parsers/rust/LICENSE"

[[annotations]]
path = ["parsers/scala/**"]
SPDX-FileCopyrightText = "Copyright (c) 2018 Max Brunsfeld and Github"
SPDX-License-Identifier = "MIT"
file = "parsers/scala/LICENSE"

[[annotations]]
path = ["parsers/solidity/**", "parsers/solidity/tree_sitter/parser.h"]
SPDX-FileCopyrightText = "Copyright (c) 2020 Joran Honig"
SPDX-License-Identifier = "MIT"
file = "parsers/swift/LICENSE"

[[annotations]]
path = ["parsers/swift/**"]
SPDX-FileCopyrightText = "Copyright (c) 2021 alex-pinkus"
SPDX-License-Identifier = "MIT"
file = "parsers/swift/LICENSE"

[[annotations]]
path = ["parsers/typescript/**", "parsers/tsx/**", "parsers/typescript/grammar.json",
"parsers/tsx/tree_sitter/parser.h"]
SPDX-FileCopyrightText = "Copyright (c) 2017 Max Brunsfeld"
SPDX-License-Identifier = "MIT"
file = "parsers/typescript/LICENSE"

[[annotations]]
path = ["parsers/yaml/**"]
SPDX-FileCopyrightText = "Copyright (c) 2019-2021 Ika; Copyright (c) 2024 tree-sitter-grammars contributors"
SPDX-License-Identifier = "MIT"
file = "parsers/yaml/LICENSE"
