# CodeWeaver Local Development Configuration
# Optimized for local development with minimal external dependencies

_config_version = "2.0"

[backend]
provider = "qdrant"
url = "http://localhost:6333"
collection_name = "code-embeddings-dev"
enable_hybrid_search = false
batch_size = 50

[provider]
embedding_provider = "sentence-transformers"
embedding_model = "all-MiniLM-L6-v2"  # Lightweight model for development
embedding_dimension = 384
use_local = true
device = "cpu"  # CPU-only for compatibility

[data_sources]
enabled = true

[[data_sources.sources]]
type = "filesystem"
enabled = true
priority = 1

[data_sources.sources.config]
root_path = "."
use_gitignore = true
patterns = ["**/*.py", "**/*.js", "**/*.ts", "**/*.md"]

[chunking]
max_chunk_size = 1000  # Smaller chunks for local testing
min_chunk_size = 50

[server]
log_level = "DEBUG"
enable_request_logging = true

# Legacy compatibility
[embedding]
provider = "sentence-transformers"
model = "all-MiniLM-L6-v2"
use_local = true

[qdrant]
url = "http://localhost:6333"
collection_name = "code-embeddings-dev"