flatten_single_child_sections: true
ignore: archive
sort:
    ignore_case: true
nav:
  # CORE: Essential for getting started
  - Home: index.md
  - Start:
      - getting-started/*
  # USE: How to integrate and use CodeWeaver
  - Use:
      - user-guide/*
  # CONFIGURE: Advanced configuration and deployment
  - Configure:
      - configuration/*
  # BUILD: For developers extending CodeWeaver
  - Contribute:
      - community/*
  - Extend:
    - extension-development/*
  - Refine:
    - intent-layer/*
  - Reference:
      - reference/*
  - API:
    - Overview: api/index.md
    - Configuration: api/config.md
    - Core Modules:
        - "api/*"
    - CLI:
        - api/cli/*
        - Commands:
            - "api/cli/commands/*"
        - CLI Utilities:
            - "api/cli/utils/*"
        - CLI Types:
            - "api/cli/types/*"
    - Architecture:
        - Backends:
            - "api/backends/*"
            - Backend Providers:
                - api/backends/providers/*
            - Backend Types:
                - api/cw_types/backends/*
        - Sources:
            - "api/sources/*"
            - Source Providers:
                - api/sources/providers/*
            - Source Types:
                - api/cw_types/sources/*
        - Providers:
            - "api/providers/*"
            - Provider Providers:
                - api/providers/providers/*
                - api/providers/nlp/*
            - Provider Types:
                - api/cw_types/providers/*
        - Middleware:
            - "api/middleware/*"
        - Services:
            - "api/services/*"
            - Service Providers:
                - api/services/providers/*
            - Service Types:
                - api/cw_types/services/*
        - Intent Layer:
            - "api/intent/*"
            - Supporting Services:
                - api/services/providers/context_intelligence.md
                - api/services/providers/implicit_learning.md
                - api/services/providers/intent_orchestrator.md
                - api/services/providers/zero_shot_optimization.md
            - Intent Types:
                - "api/cw_types/intent/*"
        - Factories:
            - "api/factories/*"
            - Factory Types:
                - api/cw_types/factories/*
    - Type System:
        - "api/cw_types/*"
    - Utilities:
        - api/utils/*
        - Testing:
            - api/testing/*
        - Language Constants:
            - api/language_constants/*

  - Enterprise:
      - enterprise/*

# - Knitli: https://knitli.com
